config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 381173 # Put your project id here

profile: default # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"
  "test_value": 123
  "holidays": ['2024-12-25', '2024-01-01', '2024-11-28']

seeds:
  jaffle_shop:
    +schema: raw

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
